"""initial schema

Revision ID: cecf94fa45b9
Revises: 
Create Date: 2026-03-17 11:50:11.868555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecf94fa45b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error_message')
    op.drop_column('tasks', 'final_output')
    op.drop_column('tasks', 'execution_started_at')
    op.drop_column('tasks', 'execution_finished_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('execution_finished_at', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('execution_started_at', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('final_output', sa.TEXT(), nullable=True))
    op.add_column('tasks', sa.Column('error_message', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
